// vue-components/src/components/SupermaticLabel.vue
<script setup lang="ts">
import type { DataBindingContainer, LabelMetadata } from "@supermatic-ui/core";
import { setupTemplate } from "@supermatic-ui/vue-core";

const props = defineProps<{ metadata: LabelMetadata; dataBinding: DataBindingContainer }>();

const label = setupTemplate(props.dataBinding, props.metadata.label.text);
const className = setupTemplate(props.dataBinding, props.metadata.className);
</script>

<template>
  <span :class="className">{{ label }}</span>
</template>

<style scoped></style>

// react-components/src/components/SupermaticLabel.tsx
import { DataBindingContainer, LabelMetadata } from "@supermatic-ui/core";
import { useTemplate } from "@supermatic-ui/react-core";

type SupermaticLabelProps = {
  metadata: LabelMetadata;
  dataBinding: DataBindingContainer;
};

const SupermaticLabel = (props: SupermaticLabelProps) => {
  const { metadata, dataBinding } = props;

  const [label] = useTemplate(dataBinding, metadata.label.text);
  const [className] = useTemplate(dataBinding, metadata.className);

  return (
    <>
      <span className={className}>{label}</span>
    </>
  );
};

export default SupermaticLabel;
