// react-core/src/components/SupermaticUi.tsx
import {
  DataBindingContainer,
  LayoutMetadata,
  Registrations,
  SchemaDefinition,
  createRegistrations,
  dataBindingBuilder,
} from "@supermatic-ui/core";
import { ComponentType, useEffect, useState } from "react";
import { useTemplate } from "../hooks";

type SupermaticUiProps = {
  configuration?: LayoutMetadata;
  onInit?: (dataBinding: DataBindingContainer) => void;
  registrations?: Registrations;
};

const SupermaticUi = (props: SupermaticUiProps) => {
  const { configuration, onInit, registrations } = props;
  const [dataBinding, setDataBinding] = useState<DataBindingContainer | null>(null);
  const [wrapClassName] = useTemplate(dataBinding, configuration?.layout.wrapClassName);

  const [components, setComponents] = useState<Record<string, ComponentType>>({});

  useEffect(() => {
    if (configuration && configuration.type === "layout") {
      console.log("[SupermaticUi] configuration", configuration);
    } else {
      console.log("[SupermaticUi] no configuration");
    }

    if (
      configuration != null &&
      configuration.dataBinding != null &&
      typeof configuration.dataBinding["type"] === "string"
    ) {
      const schemaDefinition = configuration.dataBinding as SchemaDefinition;
      const createdDataBinding = dataBindingBuilder(
        {},
        schemaDefinition,
        registrations ||
          createRegistrations({
            // TODO: Implement SupermaticContainer
            // container: SupermaticContainer,
          })
      );
      setDataBinding(createdDataBinding);
      setComponents(createdDataBinding.registrations.getComponentRegistrations());

      if (onInit) {
        onInit(createdDataBinding);
      }
    }
    //   }, [configuration, onInit, registrations]);
  }, [configuration]);

  return (
    <>
      {configuration?.layout.components.map((item, index) => {
        if (!components[item.type]) {
          return <span key={index}>Component {item.type} not found</span>;
        }
        const Component = components[item.type];
        const componentProps = { metadata: item, dataBinding };
        if (configuration?.layout.wrap) {
          return (
            <div className={wrapClassName} key={index}>
              <Component {...componentProps} key={index} />
            </div>
          );
        } else {
          return <Component {...componentProps} key={index} />;
        }
      })}
    </>
  );
};

export default SupermaticUi;

// vue-core/src/components/SupermaticUi.vue
<script setup lang="ts">
import { createRegistrations, dataBindingBuilder } from "@supermatic-ui/core";
import type { SchemaDefinition, Registrations, LayoutMetadata, DataBindingContainer } from "@supermatic-ui/core";
import { ref } from "vue";
import { setupTemplate } from "../setup";
import SupermaticContainer from "./SupermaticContainer.vue";

const props = defineProps<{
  configuration?: LayoutMetadata;
  onInit?: (dataBinding: DataBindingContainer) => void;
  registrations?: Registrations;
}>();

const wrapClassName = ref("");

if (props.configuration && props.configuration.type === "layout") {
  console.log("[SupermaticUi] configuration", props.configuration);
} else {
  console.log("[SupermaticUi] no configuration");
}

let schemaDefinition: SchemaDefinition;
let dataBinding: DataBindingContainer;

let registrations = props.registrations;
let components: Record<string, any> = {};
if (
  props.configuration != null &&
  props.configuration.dataBinding != null &&
  typeof props.configuration.dataBinding["type"] === "string"
) {
  schemaDefinition = props.configuration.dataBinding as SchemaDefinition;
  dataBinding = dataBindingBuilder(
    {},
    schemaDefinition,
    registrations ||
      createRegistrations({
        container: SupermaticContainer,
      })
  );
  components = dataBinding.registrations.getComponentRegistrations();
  setupTemplate(dataBinding, props.configuration.layout.wrapClassName, wrapClassName);

  if (props.onInit) {
    props.onInit(dataBinding);
  }
}

console.log("[SupermaticUi] components", components);
</script>

<template>
  <template v-for="(item, index) in props.configuration?.layout.components" :key="index">
    <div v-if="props.configuration?.layout.wrap" :class="wrapClassName">
      <component :is="components[item.type]" :metadata="item" :dataBinding="dataBinding"> </component>
    </div>
    <component v-else :is="components[item.type]" :metadata="item" :dataBinding="dataBinding"> </component>
  </template>
</template>

<style scoped></style>
