// vue-core/sandbox/App.vue
<script setup lang="ts">
import SupermaticUi from "../src/components/SupermaticUi.vue";
import schema from "./sandbox.json";
import { createRegistrations } from "@supermatic-ui/core";

const onInit = (dataBinding) => {
  console.log("[sandbox] onInit", dataBinding);
};
const components = {};
const registrations = createRegistrations(components);
</script>

<template>
  <h1>Supermatic UI Vue Core Sandbox</h1>
  <SupermaticUi :configuration="schema" :registrations="registrations" @init="onInit($event)"></SupermaticUi>
</template>

// react-core/sandbox/App.tsx
import React, { useState } from "react";
import { SupermaticUi } from "../src";
import { Registrations, createRegistrations } from "@supermatic-ui/core";
import schema from "./sandbox.json";

const components = {
  label: () => <div>Just hardcoded label</div>,
  input: () => <div>Just hardcoded input</div>,
};

const App = () => {
  const [registrations] = useState<Registrations>(createRegistrations(components));

  const onInit = (dataBinding) => {
    console.log("[sandbox] onInit", dataBinding);
  };

  return (
    <>
      <h1>Supermatic UI React Core Sandbox</h1>
      <SupermaticUi configuration={schema} registrations={registrations} onInit={(e) => onInit(e)}></SupermaticUi>
    </>
  );
};

export default App;
